name: News Sentiment Analysis

on:
  schedule:
    - cron: '19 19 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
        pip install transformers
        pip install -r requirements.txt

    - name: Run Python Script
      run: python Sentiment_Analysis.py

    - name: Commit and push results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add daily_sentiment_counts.csv daily_news_data.csv
        git commit -m "Update sentiment and news data" || echo "No changes to commit"
        git push
